[package]
edition = "2021"
name = "advent-of-code"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "day1"
path = "day1/main.rs"

[dependencies]
color-eyre = "0.6"
